# Generated by Django 4.1 on 2022-09-06 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='imagin',
            new_name='imagen',
        ),
    ]
